version: '3'
services:
  api:
    build: .
    command: npm start
    restart: always
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # https://stackoverflow.com/a/32785014

    ports:
      - '8081:8080'
      - '9229:9229'
